var portalHTML="<div class=\"portal\">";
portalHTML=portalHTML+"    <!--标题加上天气-->";
portalHTML=portalHTML+"    <div class=\"zz_bg_top\">";
portalHTML=portalHTML+"        <div class=\"nav-title\">";
portalHTML=portalHTML+"            <div class=\"nav-logo\">";
portalHTML=portalHTML+"                <img src=\"./Apps/img/logo.png\" alt=\"\">";
portalHTML=portalHTML+"            </div>";
portalHTML=portalHTML+"            <div class=\"nav-time\">";
portalHTML=portalHTML+"                <h1 ></h1>";
portalHTML=portalHTML+"                <p></p>";
portalHTML=portalHTML+"            </div>";
portalHTML=portalHTML+"            <div class=\"nav-weather\" >";
portalHTML=portalHTML+"                <div id=\"he-plugin-standard\"></div>";
portalHTML=portalHTML+"            </div>";
portalHTML=portalHTML+"        </div>";
portalHTML=portalHTML+"    </div>";
portalHTML=portalHTML+"    <!--平台首页-->";
portalHTML=portalHTML+"    <div id=\"ptsy\">";
portalHTML=portalHTML+"        <div class=\"zz_bg_left\">";
portalHTML=portalHTML+"            <div class=\"_platform\">";
portalHTML=portalHTML+"                <div class=\"_platformItem\">";
portalHTML=portalHTML+"                    <div class=\"plcH4\">";
portalHTML=portalHTML+"                        <h4>人员统计</h4>";
portalHTML=portalHTML+"                        <p>PERSONNEL STATISTICS</p>";
portalHTML=portalHTML+"                        <img src=\"./Apps/img/人员统计.png\" alt=\"\">";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                    <div class=\"Etcher_1\">";
portalHTML=portalHTML+"                        <div class=\"_iconFig\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/图层%2012.png\" alt=\"\">";
portalHTML=portalHTML+"                                <p>总人员数量</p>";
portalHTML=portalHTML+"                                <h3>11225人</h3>";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                        <div id=\"EtcherPerson\" style=\"width: 400px;height:190px;\"></div>";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                </div>";
portalHTML=portalHTML+"                <div class=\"_platformItem\">";
portalHTML=portalHTML+"                    <div class=\"plcH4\">";
portalHTML=portalHTML+"                        <h4>车辆统计</h4>";
portalHTML=portalHTML+"                        <p>Vehicle statistics</p>";
portalHTML=portalHTML+"                        <img src=\"./Apps/img/人员统计.png\" alt=\"\">";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                    <div class=\"Etcher_1\">";
portalHTML=portalHTML+"                        <div class=\"car_bg\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/图层%2017.png\" alt=\"\">";
portalHTML=portalHTML+"                                <p>已停车辆数量</p>";
portalHTML=portalHTML+"                                <div class=\"car_num\">";
portalHTML=portalHTML+"                                    <h4>2308</h4>";
portalHTML=portalHTML+"                                    <div class=\"car_num_line\"></div>";
portalHTML=portalHTML+"                                    <h5>4210</h5>";
portalHTML=portalHTML+"                                </div>";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                        <div class=\"car_tj\">";
portalHTML=portalHTML+"                            <div class=\"car_tj_item\">";
portalHTML=portalHTML+"                                <p>剩余车位数</p>";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/矩形%209.png\" alt=\"\">";
portalHTML=portalHTML+"                                    <h4>1902</h4>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"car_tj_dash\">";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"car_tj_item\">";
portalHTML=portalHTML+"                                <p>员工车辆数</p>";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/矩形 9 (1).png\" alt=\"\">";
portalHTML=portalHTML+"                                    <h4 style=\"color: #00CC99\">2010</h4>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"car_tj_line\">";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"car_tj_item\">";
portalHTML=portalHTML+"                                <p>访客车辆数</p>";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/矩形 9 (2).png\" alt=\"\">";
portalHTML=portalHTML+"                                    <h4 style=\"color: #0078FF\">298</h4>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                </div>";
portalHTML=portalHTML+"                <div class=\"_platformItem\" style=\"margin-top: 10px;\">";
portalHTML=portalHTML+"                    <div class=\"plcH4\">";
portalHTML=portalHTML+"                        <h4>智能告警</h4>";
portalHTML=portalHTML+"                        <p>INTELLIGENT ALARM</p>";
portalHTML=portalHTML+"                        <img src=\"./Apps/img/人员统计.png\" alt=\"\">";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                    <div class=\"Etcher_1\">";
portalHTML=portalHTML+"                        <div class=\"warning_note\">";
portalHTML=portalHTML+"                            <div class=\"warn_bg\" style=\"pointer-events: painted;\">";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/图层 21.png\" alt=\"\">";
portalHTML=portalHTML+"                                    <p>告警总数</p>";
portalHTML=portalHTML+"                                    <h4>12</h4>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"warning_item\">";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/sbgj.png\" alt=\"\">";
portalHTML=portalHTML+"                                    <p>设备告警</p>";
portalHTML=portalHTML+"                                    <h5>4</h5>";
portalHTML=portalHTML+"                                    <div class=\"warning_item_arrow\">";
portalHTML=portalHTML+"                                        <img src=\"./Apps/img/形状%2012.png\" alt=\"\">";
portalHTML=portalHTML+"                                            <p>5%</p>";
portalHTML=portalHTML+"                                    </div>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"waring-line_dash\"></div>";
portalHTML=portalHTML+"                            <div class=\"warning_item\">";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/图层 23.png\" alt=\"\">";
portalHTML=portalHTML+"                                    <p>安防告警</p>";
portalHTML=portalHTML+"                                    <h5 style=\"color:#00CC99\">4</h5>";
portalHTML=portalHTML+"                                    <div class=\"warning_item_arrow\">";
portalHTML=portalHTML+"                                        <img src=\"./Apps/img/形状 12 (1).png\" alt=\"\">";
portalHTML=portalHTML+"                                            <p>4%</p>";
portalHTML=portalHTML+"                                    </div>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"waring-line_dash\"></div>";
portalHTML=portalHTML+"                            <div class=\"warning_item\">";
portalHTML=portalHTML+"                                <img src=\"./Apps/img/图层 24.png\" alt=\"\">";
portalHTML=portalHTML+"                                    <p>能源告警</p>";
portalHTML=portalHTML+"                                    <h5 style=\"color:#0078FF\">4</h5>";
portalHTML=portalHTML+"                                    <div class=\"warning_item_arrow\">";
portalHTML=portalHTML+"                                        <img src=\"./Apps/img/形状%2012.png\" alt=\"\">";
portalHTML=portalHTML+"                                            <p>3%</p>";
portalHTML=portalHTML+"                                    </div>";
portalHTML=portalHTML+"                            </div>";
portalHTML=portalHTML+"                            <div class=\"waring-line_dash\"></div>";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                </div>";
portalHTML=portalHTML+"            </div>";
portalHTML=portalHTML+"        </div>";
portalHTML=portalHTML+"        <div class=\"zz_bg_right\">";
portalHTML=portalHTML+"            <div class=\"_platformRight\">";
portalHTML=portalHTML+"                <div class=\"_platformItemRight\">";
portalHTML=portalHTML+"                    <div class=\"plcH4\">";
portalHTML=portalHTML+"                        <h4>重点监控</h4>";
portalHTML=portalHTML+"                        <p>KEY MONITORING</p>";
portalHTML=portalHTML+"                        <img src=\"./Apps/img/人员统计.png\" alt=\"\">";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                    <div class=\"Etcher_1\" style=\"height: 230px;\">";
portalHTML=portalHTML+"                        <div class=\"video_item\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/jiankong.png\" alt=\"\">";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                        <div class=\"video_item\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/jiankong.png\" alt=\"\">";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                        <div class=\"video_item\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/jiankong.png\" alt=\"\">";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                        <div class=\"video_item\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/jiankong.png\" alt=\"\">";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                </div>";
portalHTML=portalHTML+"                <div class=\"_platformItemRight\" style=\"margin-top: 10px;height: 210px;\">";
portalHTML=portalHTML+"                    <div class=\"plcH4\">";
portalHTML=portalHTML+"                        <h4>能耗统计</h4>";
portalHTML=portalHTML+"                        <p>ENERGY CONSUMPTION STATISTICS</p>";
portalHTML=portalHTML+"                        <img src=\"./Apps/img/人员统计.png\" alt=\"\">";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                    <div class=\"Etcher_1\">";
portalHTML=portalHTML+"                        <div class=\"_iconFig\">";
portalHTML=portalHTML+"                            <img src=\"./Apps/img/图层 27.png\" alt=\"\">";
portalHTML=portalHTML+"                                <p>本月总耗电</p>";
portalHTML=portalHTML+"                                <h3 style=\"color: #0078FF;margin-left: 150px\">162.4KW</h3>";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                        <div class=\"MoveChatContent\">";
portalHTML=portalHTML+"                            <div id=\"MoveChat\" style=\"width: 220px;height:150px;\"></div>";
portalHTML=portalHTML+"                            <h4 style=\"top: 145px; left: 74px;\">月耗电同比</h4>";
portalHTML=portalHTML+"                            <div id=\"MoveChatNum\" style=\"width: 220px;height:150px;\"></div>";
portalHTML=portalHTML+"                            <h4 style=\"top: 145px;right: 70px;\">月耗电环比</h4>";
portalHTML=portalHTML+"                        </div>";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                </div>";
portalHTML=portalHTML+"                <div class=\"_platformItemRight\">";
portalHTML=portalHTML+"                    <div class=\"plcH4\">";
portalHTML=portalHTML+"                        <h4>资产统计</h4>";
portalHTML=portalHTML+"                        <p>ASSET STATISTICS</p>";
portalHTML=portalHTML+"                        <img src=\"./Apps/img/人员统计.png\" alt=\"\">";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                    <div class=\"Etcher_1\" style=\"margin-top: -30px;\">";
portalHTML=portalHTML+"                        <div id=\"EtcherMoney\" style=\"width: 400px;height:280px;\"></div>";
portalHTML=portalHTML+"                    </div>";
portalHTML=portalHTML+"                </div>";
portalHTML=portalHTML+"            </div>";
portalHTML=portalHTML+"        </div>";
portalHTML=portalHTML+"    </div>";
portalHTML=portalHTML+"    <!--导航条-->";
portalHTML=portalHTML+"    <div class=\"zz_bg_bottom\">";
portalHTML=portalHTML+"        <div id=\"navigation\"  style=\"pointer-events: painted;\">";
portalHTML=portalHTML+"            <span class=\"select_first\"><p>平台首页</p></span>";
portalHTML=portalHTML+"            <span><p>智能运维</p></span>";
portalHTML=portalHTML+"            <span><p>视频监控</p></span>";
portalHTML=portalHTML+"            <span><p>人员监控</p></span>";
portalHTML=portalHTML+"            <span><p>基础功能</p></span>";
portalHTML=portalHTML+"        </div>";
portalHTML=portalHTML+"        <div class=\"longLine\">=</div>";
portalHTML=portalHTML+"    </div>";
portalHTML=portalHTML+"    <!--基础功能导航条-->";
portalHTML=portalHTML+"    <div id=\"jcgn\"  style=\"pointer-events: painted;\">";
portalHTML=portalHTML+"        <span class=\"select_jcgn\"><p>地图书签</p></span>";
portalHTML=portalHTML+"        <span><p>属性查询</p></span>";
portalHTML=portalHTML+"        <span><p>地图量算</p></span>";
portalHTML=portalHTML+"        <span><p>路径漫游</p></span>";
portalHTML=portalHTML+"        <span><p>通视分析</p></span>";
portalHTML=portalHTML+"    </div>";
portalHTML=portalHTML+"</div>";
portalHTML=portalHTML+"<!--分析参数录入框-->";
portalHTML=portalHTML+"<div id=\"analysisConDiv\">";
portalHTML=portalHTML+"</div>";
portalHTML=portalHTML+"<!-- 功能子页容器 -->";
portalHTML=portalHTML+"<div id=\"funcDiv\" style=\"display: none;\">";
portalHTML=portalHTML+"    <div id=\"funcContent\" class=\"funcContent\">";
portalHTML=portalHTML+"        <!--子功能面板容器-->";
portalHTML=portalHTML+"    </div>";
portalHTML=portalHTML+"</div>";
portalHTML=portalHTML+"<!--告警等级div-->";
portalHTML=portalHTML+"<div id=\"warningDiv\">";
portalHTML=portalHTML+"</div>";
portalHTML=portalHTML+"<!--属性查询div-->";
portalHTML=portalHTML+"<div id=\"attributesDiv\">";
portalHTML=portalHTML+"</div>";
